### ISSUE TITLE
Allow page property on elements that are flowed into volume @begin or @end area

### ISSUE THREAD

**Issue by bertfrees** [daisy/pipeline-mod-braille#104]
The use case is the following: Mischa wants to have no footer on the first two pages (title pages), and a footer with a braille page number and the text "Klappentexte" from page 3 up to the beginning of the bodymatter.

**Comment by bertfrees** [comment]
Also make a note about this in the braille CSS specification.

**Comment by mixa72** [comment]
Just a short summary in order to be more precise:
(footers, if available, appear only on right-hand pages)
- title page (part of the frontmatter): no footer at all (no braille page number)
- rest of frontmatter: "Klappentexte" in the footer (no braille page number)
- bodymatter: footer according to h1-h6 (print page number & braille page number)

That means multiple page styles could be defined in the frontmatter.

**Comment by bertfrees** [comment]
- [ ] To do: integration test in pipeline-mod-sbs
