### ISSUE TITLE
list-style-type:none not working

### ISSUE THREAD

**Issue by matskober** [daisy/pipeline-mod-braille#167]
see job#1010, volume 19; "Ordliste".
The list is not correct rendered:
 - There should be no numbering of list (the inline style in the EPUB3 is "list-style:none")
 - the list has first line indent (as a normal paragraph), but should have "hanging indent" - e.g. no indent on first line and two indents on the following lines

@josteinaj  @bertfrees

**Comment by josteinaj** [comment]
@matskober The `list-style-type-none` class is defined like this in your EPUB:

```html
<style type="text/css" xml:space="preserve">
.list-style-type-none {
    list-style-type:none;
}
</style>
```

You may have to set the attribute `media="embossed"` on the style element to make the CSS take effect.

**Comment by josteinaj** [comment]
For reference, here's the relevant input HTML in Mats' job:

```html
<head>
    <style type="text/css" xml:space="preserve">
    .list-style-type-none {
        list-style-type:none;
    }
    </style>
</head>
<body>
    <ol id="list_1" class="list-style-type-none">
        <li id="li_1">Aegis: et skjold som Thalia Grace bruker, og som har et fryktinngytende bilde av Medusa foran. Det forvandler seg til et s&#xf8;lvarmb&#xe5;nd n&#xe5;r hun ikke bruker det</li>
        <li id="li_2">Agamethus: s&#xf8;nn av kong Erginus, halvbror av Trophonios, som hogg hodet av ham for &#xe5; unng&#xe5; &#xe5; bli oppdaget etter plyndringstoktet i kong Hyrieus&#x2019; skattkammer</li>
        <li id="li_3">Akefaloer: en stamme med hodel&#xf8;se folk med ansiktet p&#xe5; brystet</li>
        <li id="li_4">Amasoner: et folk best&#xe5;ende av kvinnelige krigere</li>
        <li id="li_5">Amfora: en h&#xf8;y vinkrukke av keramikk</li>
        <li id="li_6">Ares: den greske krigsguden. S&#xf8;nn av Zevs og Hera, og halvbror til Athene. Romersk motstykke: Mars</li>
    <!-- ... -->
</ol>
```

And here's the PEF output rows:

```xml
<row>⠀⠀⠀⠀⠀⠀⠼⠁⠀⠠⠁⠑⠛⠊⠎⠒⠀⠑⠞⠀⠎⠅⠚⠕⠇⠙⠀⠎⠕⠍</row>
<row>⠀⠀⠀⠀⠠⠞⠓⠁⠇⠊⠁⠀⠠⠛⠗⠁⠉⠑⠀⠃⠗⠥⠅⠑⠗⠂⠀⠕⠛</row>
<row>⠀⠀⠀⠀⠎⠕⠍⠀⠓⠁⠗⠀⠑⠞⠀⠋⠗⠽⠅⠞⠊⠝⠝⠛⠽⠞⠑⠝⠙⠑</row>
<row>⠀⠀⠀⠀⠃⠊⠇⠙⠑⠀⠁⠧⠀⠠⠍⠑⠙⠥⠎⠁⠀⠋⠕⠗⠁⠝⠄</row>
<row>⠀⠀⠀⠀⠠⠙⠑⠞⠀⠋⠕⠗⠧⠁⠝⠙⠇⠑⠗⠀⠎⠑⠛⠀⠞⠊⠇⠀⠑⠞</row>
<row>⠀⠀⠀⠀⠎⠪⠇⠧⠁⠗⠍⠃⠡⠝⠙⠀⠝⠡⠗⠀⠓⠥⠝⠀⠊⠅⠅⠑</row>
<row>⠀⠀⠀⠀⠃⠗⠥⠅⠑⠗⠀⠙⠑⠞</row>
<row>⠀⠀⠀⠀⠀⠀⠼⠃⠀⠠⠁⠛⠁⠍⠑⠞⠓⠥⠎⠒⠀⠎⠪⠝⠝⠀⠁⠧</row>
<row>⠀⠀⠀⠀⠅⠕⠝⠛⠀⠠⠑⠗⠛⠊⠝⠥⠎⠂⠀⠓⠁⠇⠧⠃⠗⠕⠗⠀⠁⠧</row>
<row>⠀⠀⠀⠀⠠⠞⠗⠕⠏⠓⠕⠝⠊⠕⠎⠂⠀⠎⠕⠍⠀⠓⠕⠛⠛⠀⠓⠕⠙⠑⠞</row>
<row>⠀⠀⠀⠀⠁⠧⠀⠓⠁⠍⠀⠋⠕⠗⠀⠡⠀⠥⠝⠝⠛⠡⠀⠡⠀⠃⠇⠊</row>
<row>⠀⠀⠀⠀⠕⠏⠏⠙⠁⠛⠑⠞⠀⠑⠞⠞⠑⠗⠀⠏⠇⠽⠝⠙⠗⠊⠝⠛⠎⠤</row>
<row>⠀⠀⠀⠀⠞⠕⠅⠞⠑⠞⠀⠊⠀⠅⠕⠝⠛⠀⠠⠓⠽⠗⠊⠑⠥⠎⠐</row>
<row>⠀⠀⠀⠀⠎⠅⠁⠞⠞⠅⠁⠍⠍⠑⠗</row>
<row>⠀⠀⠀⠀⠀⠀⠼⠉⠀⠠⠁⠅⠑⠋⠁⠇⠕⠑⠗⠒⠀⠑⠝⠀⠎⠞⠁⠍⠍⠑</row>
<row>⠀⠀⠀⠀⠍⠑⠙⠀⠓⠕⠙⠑⠇⠪⠎⠑⠀⠋⠕⠇⠅⠀⠍⠑⠙</row>
<row>⠀⠀⠀⠀⠁⠝⠎⠊⠅⠞⠑⠞⠀⠏⠡⠀⠃⠗⠽⠎⠞⠑⠞</row>
<row>⠀⠀⠀⠀⠀⠀⠼⠙⠀⠠⠁⠍⠁⠎⠕⠝⠑⠗⠒⠀⠑⠞⠀⠋⠕⠇⠅⠀⠃⠑⠤</row>
<row>⠀⠀⠀⠀⠎⠞⠡⠑⠝⠙⠑⠀⠁⠧⠀⠅⠧⠊⠝⠝⠑⠇⠊⠛⠑</row>
<row>⠀⠀⠀⠀⠅⠗⠊⠛⠑⠗⠑</row>
<row>⠀⠀⠀⠀⠀⠀⠼⠑⠀⠠⠁⠍⠋⠕⠗⠁⠒⠀⠑⠝⠀⠓⠪⠽⠀⠧⠊⠝⠤</row>
<row>⠀⠀⠀⠀⠅⠗⠥⠅⠅⠑⠀⠁⠧⠀⠅⠑⠗⠁⠍⠊⠅⠅</row>
<row>⠀⠀⠀⠀⠀⠀⠼⠋⠀⠠⠁⠗⠑⠎⠒⠀⠙⠑⠝⠀⠛⠗⠑⠎⠅⠑</row>
<row>⠀⠀⠀⠀⠅⠗⠊⠛⠎⠛⠥⠙⠑⠝⠄⠀⠠⠎⠪⠝⠝⠀⠁⠧⠀⠠⠵⠑⠧⠎</row>
<row>⠀⠀⠀⠀⠕⠛⠀⠠⠓⠑⠗⠁⠂⠀⠕⠛⠀⠓⠁⠇⠧⠃⠗⠕⠗⠀⠞⠊⠇</row>
<row>⠀⠀⠀⠀⠠⠁⠞⠓⠑⠝⠑⠄⠀⠠⠗⠕⠍⠑⠗⠎⠅⠀⠍⠕⠞⠤</row>
<row>⠀⠀⠀⠀⠎⠞⠽⠅⠅⠑⠒⠀⠠⠍⠁⠗⠎</row>
```

**Comment by josteinaj** [comment]
Your example is an ordered list, and it's not preformatted (i.e. no "•" or similar characters inline at the start of each `<li>`). The `list-style-type` CSS property can be used to change if and how the list is numbered/bulleted.

For testing, you could also try setting the attribute `style="list-style-type: none;"` on the `<li>` elements explicitly. Maybe there's an issue with priorities when using the NLB stylesheet as well as `<style>` elements.

The indentation of the first line of list items is specified with `text-indent` property and is independent of the `list-style-type` attribute. It is set to `2` in NLBs default stylesheet. If you think the whole list item should be indented and not just the first line, we could maybe use `margin-left: 2;` instead.

However, if this is an issue specific to how NLB should render braille, then you can open an issue on [nlbdev/pipeline](/nlbdev/pipeline) instead.

**Comment by josteinaj** [comment]
Actually, I think maybe you've placed the class attribute in your EPUB wrong. I think you should put the `list-style-type-none` class on each `<li>` element instead. Or you can change the CSS rule to:

```css
li {
    list-style-type:none;
}
```

**Comment by matskober** [comment]
Well, I haven't done anything in the EPUB; it is generated from the DTBook's <list type="pl">

**Comment by bertfrees** [comment]
Side note: `list-style` is an alias of `list-style-type`.

**Comment by josteinaj** [comment]
@bertfrees aha, I didn't know that.

@matskober Ok, then I suppose the input DTBook was a preformatted list and the CSS rule in the output is maybe wrong. In any case the CSS generated by the nordic migrator when converting a dtbook to epub is not intended to be used when embossing braille.

**Comment by matskober** [comment]
OK, I thought it would be similar to the one I started out with; that EPUB3 to DTBook and back to EPUB3 would be a kind of a "round trip". And why does it matter, what the EPUB-css looks like; I thought the main css in PIP was in charge?

**Comment by josteinaj** [comment]
Yes it is supposed to be a round trip, so that the EPUB3 you put in and get out are essentially the same. But the DTBook to EPUB 3 script has not been used as much as the EPUB 3 to DTBook script, so maybe there are bugs in that script still.

It shouldn't matter what the EPUB CSS looks like, no. Practically all of the CSS is in NLBs stylesheet, we don't have some shared CSS across organizations.

**Comment by bertfrees** [comment]
Is this a real issue in pipeline-mod-braille?

**Comment by matskober** [comment]
Not sure what you are asking, @bertfrees

**Comment by bertfrees** [comment]
Just trying to find out whether this is an issue specific to NLB, or if there's a bug in the Pipeline according to you, or something else.

So if I understand correctly your issue is that the CSS `list-style-type:none;` embedded in your EPUB has no effect? Have you got the option "Apply document-specific CSS" enabled? (see http://daisy.github.io/pipeline/modules/braille/epub3-to-pef)

**Comment by matskober** [comment]
Ok. The problem, as far as I remember, was that PIP generated list numbering when I didn't expect it. The list-style-type: none was present in the xhtml, I believe.

**Comment by bertfrees** [comment]
The CSS in the xhtml is expected to be ignored when the "Apply document-specific CSS" option is not enabled.

**Comment by matskober** [comment]
OK. Is it only ol and ul in xhtml? How should the EPUB be marked up, if
there is not to be applied any list marks, neither number nor bullets? If
the EPUB is based upon a PDF, specially a scanned PDF, the list marks are
already there. So maybe the default should be not to add any list style?

**Comment by bertfrees** [comment]
Yes, it's only ol and ul, XHTML hasn't got an element specially for preformatted lists. The default in CSS is numbers for ol and bullets for ul, which matches the semantics. I try to stay as faithful as possible to the CSS standard. So the default should stay like it is now I think.

But it isn't hard to apply a different style. If I understand correctly you already mark up preformatted lists with the class "list-style-type-none" today, and you even have the right CSS embedded in the EPUB 3. All you need to do is either enable the "Apply document-specific CSS" option, or provide the style via an external style sheet. If you are afraid that enabling the "Apply document-specific CSS" option would mess things up because there are also rules that should not be applied, you can split up the embedded style sheet in a "screen" part and an "embossed" part.

```html
<link rel="stylesheet" type="text/css" media="screen" href="main.xsl"/>
<link rel="stylesheet" type="text/css" media="embossed" href="braille-specific.xsl"/>
```

**Comment by matskober** [comment]
Thanks, Bert, that was informativ!
